name: dart_get_up_to_speed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/JustForWorld/Learn-Langs

environment:
  sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
